(* DO NOT EDIT THIS FILE. 
   You will not be submitting it, so we 
   will never see your edits. If you change this file, your code 
   will probably not compile when you submit. *)


type 'a queue 

(* examples from class *)
val create : unit -> 'a queue
val is_empty : 'a queue -> bool
val enq : 'a -> 'a queue -> unit
val deq : 'a queue -> 'a 
val length : 'a queue -> int
val to_list : 'a queue -> 'a list
  
(* New operations *)
val from_list : 'a list -> 'a queue
val valid : 'a queue -> bool 
val print : 'a queue -> ('a -> string) -> unit

val contains : 'a -> 'a queue -> bool
val truncate : 'a -> 'a queue -> unit
val delete : 'a -> 'a queue -> unit

(* Kudos operation *)
val has_cycle : 'a queue -> bool
